/**
 * R3.1 — the app entry point.
 *
 * Boot order matters and is deliberately explicit:
 *
 *  1. settings (the persisted language must be known *before* the first render,
 *     so a reload does not flash the fallback language);
 *  2. language packs — the canonical pack (`en_US`) plus whatever else ships in
 *     `lang/`. A user pack dropped next to them is picked up by the same code
 *     path (R1.2e / iron law 7: a new language is one JSON file);
 *  3. the shipped configuration, so a first-time user has something to edit;
 *  4. the shell.
 */

import enMessages from '../../../lang/en_US.messages.json';
import enApp from '../../../lang/en_US.app.json';
import zhMessages from '../../../lang/zh_CN.messages.json';
import zhApp from '../../../lang/zh_CN.app.json';
import zhElements from '../../../lang/zh_CN.elements.json';
// R5.2 — the third locale, and the proof that adding one is data, not code: this import
// plus the one `loadPack()` line below is the entire change. No TypeScript file knows what
// a locale is, and `lang/ja_JP.app.json` is generated by `tools/ts/make-locale.mjs`.
import jaApp from '../../../lang/ja_JP.app.json';
import nuclearcraft from '../../../datasets/configurations/nuclearcraft.ncpf.json';
// R4.4 — the four shipped generator presets. Inlined the same way the configuration is
// (R3.1's "open the app is one request"), so the generator works offline and needs no
// extra fetch. Each preset carries its own stripped configuration, which is what the
// index translation in `model/generatorHost.ts` reads.
import overhaulEfficiency from '../../../datasets/configurations/generators/overhaul_sfr/efficiency.ncpf.json';
import overhaulOutput from '../../../datasets/configurations/generators/overhaul_sfr/output.ncpf.json';
import underhaulEfficiency from '../../../datasets/configurations/generators/underhaul_sfr/efficiency.ncpf.json';
import underhaulOutput from '../../../datasets/configurations/generators/underhaul_sfr/output.ncpf.json';
import { loadPack, type LanguagePack } from '@ncplanner/i18n';
import { browserStorage, SettingsStore } from './settings.js';
import { AppI18n } from './i18n.js';
import { AppDocument } from './model/document.js';
import { PlannerApp } from './ui/app.js';
import { readAnyProjectText } from '@ncplanner/formats';

/** Built-in packs; `lang/*.app.json` is merged into the migrated R1.2 packs. */
export function builtinPacks(): LanguagePack[] {
  return [
    loadPack(enMessages),
    loadPack(enApp),
    loadPack(zhMessages),
    loadPack(zhApp),
    loadPack(zhElements),
    loadPack(jaApp),
  ];
}

export function bootstrap(root: HTMLElement): PlannerApp {
  const settings = new SettingsStore({ storage: browserStorage() });
  const i18n = new AppI18n({ packs: builtinPacks(), settings });
  const project = readAnyProjectText(JSON.stringify(nuclearcraft), 'nuclearcraft.ncpf.json').document;
  const app = new PlannerApp({
    root,
    i18n,
    settings,
    defaultProject: project,
    generatorPresets: {
      'overhaul_sfr/efficiency': overhaulEfficiency,
      'overhaul_sfr/output': overhaulOutput,
      'underhaul_sfr/efficiency': underhaulEfficiency,
      'underhaul_sfr/output': underhaulOutput,
    },
  });
  // Exposed for the manual walkthrough and for CI smoke checks in a real DOM.
  (globalThis as { ncplanner?: unknown }).ncplanner = { app, settings, i18n, AppDocument };
  return app;
}

const root = document.getElementById('app');
if (root !== null) bootstrap(root);
