package net.ncplanner.plannerator.planner.localization;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/** Chinese UI catalogue; longer entries are applied before their fragments. */
final class SimplifiedChineseLocalizer implements TextLocalizer{
    private final List<Map.Entry<String, String>> entries = new ArrayList<>();
    private final Map<String, String> cache = new ConcurrentHashMap<>();

    SimplifiedChineseLocalizer(){
        Map<String, String> translations = new LinkedHashMap<>();
        add(translations,
                "Nuclearcraft Plannerator", "核工艺规划器",
                "DSSL Editor", "DSSL 编辑器",
                "RECOVERY MODE ENABLED. PRESS CTRL+SHIFT+R TO DISABLE", "恢复模式已启用。按 Ctrl+Shift+R 关闭",
                "Press escape to exit credits", "按 Esc 退出致谢名单",
                "Open a link? (Will open in default browser)", "要打开链接吗？（将在默认浏览器中打开）",
                "Would you like to save?", "是否保存？",
                "Unsaved changes detected!\nSave changes?", "检测到未保存的更改！\n是否保存？",
                "Delete the currently selected multiblock\nWARNING: This cannot be undone!", "删除当前选中的多方块结构\n警告：此操作无法撤销！",
                "Stop editing this multiblock and return to the main menu", "停止编辑此多方块结构并返回主菜单",
                "Resize the multiblock\nWARNING: This clears the edit history! (undo/redo)", "调整多方块结构尺寸\n警告：这会清除编辑历史记录（撤销/重做）！",
                "Toggle 3D multiblock view\n(Rotate with arrow keys)", "切换多方块结构的 3D 视图\n（使用方向键旋转）",
                "Recalculate the entire multiblock\nCtrl-click to queue multiple actions without recalculating", "重新计算整个多方块结构\n按住 Ctrl 单击可将多个操作加入队列而不立即计算",
                "Convert the currently selected multiblock to an Overhaul MSR\nWARNING: All fuels will be converted to their Flouride counterparts", "将当前选中的多方块结构转换为改版熔盐堆\n警告：所有燃料都会转换为对应的氟化物",
                "Convert the currently selected multiblock to an Overhaul SFR\nWARNING: All fuels will be converted to their Oxide counterparts", "将当前选中的多方块结构转换为改版固体燃料堆\n警告：所有燃料都会转换为对应的氧化物",
                "Click or drop files to change ", "单击或拖入文件以更换",
                " texture\nOr right click to generate a texture", "纹理\n右键单击可生成纹理",
                "Import all multiblocks from a saved file", "从已保存的文件导入全部多方块结构",
                "Export the selected multiblock to a file", "将选中的多方块结构导出到文件",
                "Save all multiblocks to a file", "将全部多方块结构保存到文件",
                "Load a file, replacing all current multiblocks", "加载文件并替换当前全部多方块结构",
                "Finish editing metadata", "完成编辑元数据",
                "Modify the multiblock metadata", "修改多方块结构元数据",
                "Generate or improve this multiblock", "生成或优化此多方块结构",
                "View a parts list for this multiblock", "查看此多方块结构的部件清单",
                "Perform one step of calculation", "执行一步计算",
                "Use Arrow keys to rotate preview", "使用方向键旋转预览",
                "Press escape or right click to exit.", "按 Esc 或右键退出。",
                "CURSOR CALIBRATION", "光标校准",
                "Calibration changed! Would you like to adjust GUI scale to match?", "校准已更改。是否同步调整界面缩放？",
                "No lite model exists for ", "不存在轻量模型：",
                "Failed to load configuration!", "加载配置失败！",
                "Failed to save script!", "保存脚本失败！",
                "Failed to export multiblock!", "导出多方块结构失败！",
                "Failed to load last configuration: ", "加载上次的配置失败：",
                "Failed to load internal texture for MSR Block: ", "加载熔盐堆方块的内部纹理失败：",
                "File ", "文件 ",
                " already exists!\nOverwrite?", " 已存在！\n是否覆盖？",
                "Saved as ", "已保存为 ",
                "Invalid filename: ", "无效的文件名：",
                "Multiblock does not exist!\nMultiblocks may still be loading", "多方块结构不存在！\n多方块结构可能仍在加载中",
                "Open Folder", "打开文件夹",
                "Save Dialog", "另存为对话框",
                "Choose Benchmark", "选择基准测试",
                "Benchmark not found", "未找到基准测试",
                "Running Benchmark: ", "正在运行基准测试：",
                "Calculating Multiblock", "正在计算多方块结构",
                "Calculating suggestions", "正在计算建议",
                "Generating suggestions", "正在生成建议",
                "Consolidating suggestions", "正在合并建议",
                "Sorting suggestions", "正在排序建议",
                "Pruning Suggestions", "正在筛选建议",
                "Calculating Casing", "正在计算外壳",
                "Calculating Heatsinks", "正在计算散热器",
                "Calculating Heaters", "正在计算加热器",
                "Calculating Bearing", "正在计算轴承",
                "Calculating Blades", "正在计算叶片",
                "Calculating Rotor", "正在计算转子",
                "Calculating Coils", "正在计算线圈",
                "Calculating Breeding Blankets", "正在计算增殖包层",
                "Building Vessel Groups", "正在构建燃料容器组",
                "Building Clusters", "正在构建簇",
                "Calculating Clusters", "正在计算簇",
                "Calculating Stats", "正在计算统计数据",
                "Calculating Shutdown Factor", "正在计算停堆系数",
                "Calculating Partial Shutdown", "正在计算部分停堆",
                "Checking Casing", "正在检查外壳",
                "Calculating Core", "正在计算核心",
                "Calculating Coolers", "正在计算冷却器",
                "Opening Neutron Shields", "正在开启中子屏蔽器",
                "Closing Neutron Shields", "正在关闭中子屏蔽器",
                "Resetting Neutron Shields", "正在重置中子屏蔽器",
                "Propogating Neutron Flux", "正在传播中子通量",
                "Re-propogating Neutron Flux", "正在重新传播中子通量",
                "Performing Post-Flux Calculations", "正在执行通量后计算",
                "Initializing Fuel Cells", "正在初始化燃料单元",
                "Initializing Fuel Vessels", "正在初始化燃料容器",
                "Initializing...", "正在初始化…",
                "Resetting Metadata", "正在重置元数据",
                "Adding File Readers...", "正在添加文件读取器…",
                "Preloading settings...", "正在预加载设置…",
                "Adding modules...", "正在添加模块…",
                "Loading settings...", "正在加载设置…",
                "Refreshing modules...", "正在刷新模块…",
                "Initializing Nuclearcraft Configuration", "正在初始化核工艺配置",
                "Adjusting MSR block textures...", "正在调整熔盐堆方块纹理…",
                "Imposing Configuration...", "正在应用配置…",
                "Adding Core Module", "正在添加核心模块",
                "Adding Underhaul Module", "正在添加旧版模块",
                "Adding Overhaul Module", "正在添加改版模块",
                "Adding Fusion Test Module", "正在添加聚变测试模块",
                "Adding Rainbow Factor Module", "正在添加彩虹因子模块",
                "Adding Prime Fuel Module", "正在添加高级燃料模块",
                "Adding Quantum Traversed Efficiency Module", "正在添加量子传输效率模块",
                "Adding Additional Modules", "正在添加附加模块",
                "Thank you to my patrons:", "感谢以下赞助者：",
                "If you enjoy this plannerator, consider supporting me on patreon or ko-fi:", "如果你喜欢这个规划器，可以在 Patreon 或 Ko-fi 上支持作者：",
                "Join my discord server:", "加入 Discord 服务器：",
                "This is for correcting a cursor offset issue on macOS", "此功能用于修正 macOS 上的光标偏移问题",
                "To auto-calibrate, click the squares that appear onscreen.", "要自动校准，请单击屏幕上出现的方块。",
                "Use arrow keys or WASD to manually adjust calibration (Press control for granular adjustment)", "使用方向键或 WASD 手动调整校准（按住 Ctrl 可进行微调）",
                "Press Delete to reset calibration", "按 Delete 重置校准",
                "NuclearCraft Planner File", "核工艺规划器文件",
                "Internal Configurations", "内置配置",
                "External Configurations", "外部配置",
                "Current Configuration", "当前配置",
                "Current Configuration: ", "当前配置：",
                "Load configuration from a file, replacing the current configuration\nAny existing multiblocks will be converted to the new configuration\nYou can load the following files:\nnuclearcraft.cfg in the game files\nany .ncpf configuration file", "从文件加载配置并替换当前配置\n已有的多方块结构将转换为新配置\n可加载以下文件：\n游戏文件中的 nuclearcraft.cfg\n任意 .ncpf 配置文件",
                "Save the configuration to a .ncpf file", "将配置保存为 .ncpf 文件",
                "Modify the current configuration", "修改当前配置",
                "Remember the selected configuration, and load it on startup.\nThis will not remember changes to the configuration, you still have to save those!", "记住所选配置，并在启动时加载。\n不会记住配置改动，仍需手动保存！",
                "Show 3D view on the Main Menu", "在主菜单显示 3D 视图",
                "Replace the current configuration with ", "使用以下配置替换当前配置：",
                "\nAll multiblocks will be converted to the new configuration", "\n所有多方块结构将转换为新配置",
                "Loading External Configurations...", "正在加载外部配置…",
                "Loading Files", "正在加载文件",
                "Failed to read external configuration ", "读取外部配置失败：",
                "Importing Configuration", "正在导入配置",
                "Finish generation and return to the editor", "完成生成并返回编辑器",
                "Finish resizing and return to the editor screen", "完成调整尺寸并返回编辑器",
                "Previous stage", "上一阶段",
                "Next stage", "下一阶段",
                "Add a generation stage", "添加生成阶段",
                "Add Thread", "添加线程",
                "Remove Thread", "移除线程",
                "Start/Stop generation", "开始/停止生成",
                "Delete Stage (Hold Shift)", "删除阶段（按住 Shift）",
                "Generator Presets", "生成器预设",
                "New Preset", "新建预设",
                "Load Generator Settings", "加载生成器设置",
                "Save Generator Settings", "保存生成器设置",
                "Finish Customizing", "完成自定义",
                "Generator Parameters", "生成器参数",
                "Add Parameter", "添加参数",
                "Mutator Settings", "变异器设置",
                "Add Mutator", "添加变异器",
                "Post-Processing Mutators", "后处理变异器",
                "Add Post-Processing Mutator", "添加后处理变异器",
                "Stage Transitions", "阶段转换",
                "Add Transition", "添加转换",
                "Add Priority", "添加优先级",
                "Add Condition", "添加条件",
                "Reset to stage 0", "重置到第 0 阶段",
                "Insert a blank layer", "插入空白层",
                "Delete this layer", "删除此层",
                "Add a blank row", "添加空白行",
                "Add a blank column", "添加空白列",
                "Delete this row", "删除此行",
                "Delete this column", "删除此列",
                "increase the reactor's Inner Radius", "增加反应堆内半径",
                "decrease the reactor's Inner Radius", "减小反应堆内半径",
                "increase the reactor's Core Size", "增加反应堆核心尺寸",
                "decrease the reactor's Core Size", "减小反应堆核心尺寸",
                "increase the reactor's Toroid Width", "增加反应堆环宽",
                "decrease the reactor's Toroid Width", "减小反应堆环宽",
                "Subtract configuration? (Convert to addon)", "要相减配置吗？（转换为附加组件）",
                "Automatic Add String", "自动添加字符串",
                "Change Target", "更改目标",
                "Import Addon", "导入附加组件",
                "Create Addon", "创建附加组件",
                "Importing addons...", "正在导入附加组件…",
                "Failed to import addon!", "导入附加组件失败！",
                "Failed to load addon", "加载附加组件失败",
                "New version available!\n(Version ", "有新版本可用！\n（版本 ",
                ")\nWould you like to update now?", "）\n是否立即更新？",
                "Failed to update!", "更新失败！",
                "Delete Multiblock (Hold Shift)", "删除多方块结构（按住 Shift）",
                "Convert to MSR (Hold Control)", "转换为熔盐堆（按住 Ctrl）",
                "Convert to SFR (Hold Control)", "转换为固体燃料堆（按住 Ctrl）",
                "Edit Metadata", "编辑元数据",
                "Block Recipe", "方块配方",
                "Actual Expansion", "实际膨胀率",
                "Queue Actions", "操作入队",
                "Main Menu", "主菜单",
                "Add Multiblock", "添加多方块结构",
                "Add a new multiblock", "添加新的多方块结构",
                "Multiblocks", "多方块结构",
                "Multiblock", "多方块结构",
                "Configurations", "配置",
                "Configuration", "配置",
                "Display Name", "显示名称",
                "Metadata", "元数据",
                "Blockstate", "方块状态",
                "Placement Rules", "放置规则",
                "Other Modules", "其他模块",
                "Element Stack", "元素堆栈",
                "Add Element Stack", "添加元素堆栈",
                "Add Element", "添加元素",
                "Add State", "添加状态",
                "Add Rule", "添加规则",
                "Delete Rule", "删除规则",
                "Modify Rule", "修改规则",
                "Parts List", "部件清单",
                "3D View", "3D 视图",
                "Zoom out", "缩小",
                "Zoom in", "放大",
                "Save as...", "另存为…",
                "Don't Save", "不保存",
                "Search", "搜索",
                "Category", "分类",
                "Tutorials", "教程",
                "Tutorial", "教程",
                "Settings", "设置",
                "Addons", "附加组件",
                "Addon", "附加组件",
                "Version", "版本",
                "Edit", "编辑",
                "Create", "创建",
                "Automatic", "自动",
                "Target", "目标",
                "String", "字符串",
                "V-Sync", "垂直同步",
                "Internal", "内部",
                "External", "外部",
                "Selected", "所选",
                "Invert", "反转",
                "Auto-build", "自动构建",
                "Casings", "外壳",
                "Remember", "记住",
                "Show", "显示",
                "Change", "更改",
                "Generator", "生成器",
                "Preset", "预设",
                "Customize", "自定义",
                "Parameters", "参数",
                "Parameter", "参数",
                "Mutators", "变异器",
                "Mutator", "变异器",
                "Post-Processing", "后处理",
                "Priorities", "优先级",
                "Priority", "优先级",
                "Transitions", "转换",
                "Transition", "转换",
                "Conditions", "条件",
                "Condition", "条件",
                "Stage", "阶段",
                "Thread", "线程",
                "Threads", "线程",
                "Start", "开始",
                "Stop", "停止",
                "Reset", "重置",
                "Volume", "体积",
                "Ideal Expansion", "理想膨胀率",
                "Themes", "主题",
                "Modules", "模块",
                "Overlays", "叠加层",
                "Symmetry", "对称",
                "Resize", "调整尺寸",
                "Generate", "生成",
                "Recalculate", "重新计算",
                "Calculate", "计算",
                "Back", "返回",
                "Undo", "撤销",
                "Redo", "重做",
                "Import", "导入",
                "Export", "导出",
                "Save", "保存",
                "Load", "加载",
                "Open", "打开",
                "New", "新建",
                "Exit", "退出",
                "Run", "运行",
                "Debug", "调试",
                "Step", "单步",
                "Continue", "继续",
                "Halt", "停止",
                "Saved", "已保存",
                "Done", "完成",
                "Cancel", "取消",
                "Close", "关闭",
                "Discard", "丢弃",
                "Yes", "是",
                "No", "否",
                "OK", "确定",
                "Filename", "文件名",
                "File", "文件",
                "Key", "键",
                "Value", "值",
                "Name", "名称",
                "Author", "作者",
                "Description", "描述",
                "Credits", "致谢",
                "Changelog", "更新日志",
                "Supporters", "支持者",
                "Active", "已启用",
                "Inactive", "未启用",
                "On", "开",
                "Off", "关",
                "Warning", "警告",
                "Error", "错误",
                "Loading", "正在加载",
                "Initializing", "正在初始化",
                "Failed", "失败",
                "Unknown", "未知",
                "Light", "浅色",
                "General", "通用",
                "Materials", "材料",
                "Water", "水",
                "Iron", "铁",
                "Redstone", "红石",
                "Quartz", "石英",
                "Obsidian", "黑曜石",
                "Gold", "金",
                "Diamond", "钻石",
                "Emerald", "绿宝石",
                "Copper", "铜",
                "Tin", "锡",
                "Lead", "铅",
                "Boron", "硼",
                "Lithium", "锂",
                "Magnesium", "镁",
                "Silver", "银",
                "Fluorite", "萤石",
                "Graphite", "石墨",
                "Helium", "氦",
                "Enderium", "末影合金",
                "Cryotheum", "极寒之凛冰",
                "Beryllium", "铍",
                "NuclearCraft Plannerator", "核工艺规划器",
                "CONTAINS LOTS OF FLASHING COLORS\nCONTINUE?", "包含大量闪烁颜色\n是否继续？",
                "Convert the currently selected multiblock to an Overhaul MSR\nWARNING: All fuels will be converted to their Flouride counterparts", "将当前选中的多方块结构转换为改版熔盐堆\n警告：所有燃料都会转换为对应的氟化物",
                "Convert the currently selected multiblock to an Overhaul SFR\nWARNING: All fuels will be converted to their Oxide counterparts", "将当前选中的多方块结构转换为改版固体燃料堆\n警告：所有燃料都会转换为对应的氧化物",
                "Configuration is Empty!", "配置为空！",
                "Overhaul Fusion Configuration is incomplete!", "改版聚变配置不完整！",
                "Overhaul MSR Configuration is incomplete!", "改版熔盐堆配置不完整！",
                "Overhaul SFR Configuration is incomplete!", "改版固体燃料堆配置不完整！",
                "Overhaul Turbine Configuration is incomplete!", "改版涡轮机配置不完整！",
                "Underhaul SFR Configuration is incomplete!", "旧版固体燃料堆配置不完整！",
                "Load configuration from a file, replacing the current configuration\nAny existing multiblocks will be converted to the new configuration\nYou can load the following files:\nnuclearcraft.cfg in the game files\nany .ncpf configuration file", "从文件加载配置并替换当前配置\n已有的多方块结构将转换为新配置\n可加载以下文件：\n游戏文件中的 nuclearcraft.cfg\n任意 .ncpf 配置文件",
                "Remember the selected configuration, and load it on startup.\nThis will not remember changes to the configuration, you still have to save those!", "记住所选配置，并在启动时加载。\n不会记住配置改动，仍需手动保存！",
                "For Axial, this is the number of axial pairs (not single blocks)", "对于轴向规则，此数值为轴向配对数（而非单个方块数）",
                "increase the reactor's Lining Thickness", "增加反应堆内衬厚度",
                "decrease the reactor's Lining Thickness", "减小反应堆内衬厚度",
                "Include Casing in Parts List", "在部件清单中包含外壳",
                "Include Casing in 3D View", "在 3D 视图中包含外壳",
                "Legacy NCPF (Config2) format, GUI, and some more internal functionality based on SimpleLibraryPlus", "旧版 NCPF（Config2）格式、界面及部分内部功能基于 SimpleLibraryPlus",
                "Unable to download patrons list! This list may be outdated.", "无法下载赞助者名单！此名单可能不是最新版本。",
                "If you have any idea what actually causes the cursor offset, please let me know", "如果你知道光标偏移的实际原因，请告诉作者。",
                "Thank you to everyone in the eVault for helping make this planner into what it is", "感谢 eVault 的每一位成员，帮助这个规划器成为今天的样子。",
                "Thank you to tomdodd4598 for creating such an amazing mod", "感谢 tomdodd4598 创作了如此出色的模组。",
                "Click on any configuration to navigate to its CurseForge page", "单击任意配置可前往其 CurseForge 页面",
                "Click on any addon to navigate to its CurseForge page", "单击任意附加组件可前往其 CurseForge 页面",
                "(a fork of Simplelibrary by computerneek)", "（Simplelibrary 的 computerneek 分支）",
                "JDA (when running as discord bot)", "JDA（作为 Discord 机器人运行时）",
                "by Gliese 832 c", "作者：Gliese 832 c",
                "by tomdodd4598", "作者：tomdodd4598",
                "by dtinth", "作者：dtinth",
                "New version available!\n(Version ", "有新版本可用！\n（版本 ",
                ")\nWould you like to update now?", "）\n是否立即更新？",
                "Unsaved changes detected!\nSave changes?", "检测到未保存的更改！\n是否保存？",
                "Delete the currently selected multiblock\nWARNING: This cannot be undone!", "删除当前选中的多方块结构\n警告：此操作无法撤销！",
                "Resize the multiblock\nWARNING: This clears the edit history! (undo/redo)", "调整多方块结构尺寸\n警告：这会清除编辑历史记录（撤销/重做）！",
                "Toggle 3D multiblock view\n(Rotate with arrow keys)", "切换多方块结构的 3D 视图\n（使用方向键旋转）",
                "Recalculate the entire multiblock\nCtrl-click to queue multiple actions without recalculating", "重新计算整个多方块结构\n按住 Ctrl 单击可将多个操作加入队列而不立即计算",
                "Color (decimal; prefix with # for hex)", "颜色（十进制；十六进制请加 # 前缀）",
                "Configurations (Modpacks)", "配置（整合包）",
                "Addons, Mods, & Modpacks", "附加组件、模组和整合包",
                "Add Global Elements", "添加全局元素",
                "Add Parent ", "添加父项 ",
                "Choose Element Definition", "选择元素定义",
                "Choose Mutator Type", "选择变异器类型",
                "Choose Parameter Name", "选择参数名称",
                "Choose a mutator", "选择变异器",
                "Choose a parameter", "选择参数",
                "Critical Error: ", "严重错误：",
                "Delete this generation stage", "删除此生成阶段",
                "Different theme font", "另类主题字体",
                "Fusion test blanket textures", "聚变测试包层纹理",
                "Generate Texture", "生成纹理",
                "Include 3D View", "包含 3D 视图",
                "Include Casing", "包含外壳",
                "Lining Thickness", "内衬厚度",
                "Load this addon", "加载此附加组件",
                "Modify multiblock", "修改多方块结构",
                "Modify Block (Overhaul SFR)", "修改方块（改版固体燃料堆）",
                "Placement Rule", "放置规则",
                "Remove or Delete Addon", "移除或删除附加组件",
                "System File Chooser", "系统文件选择器",
                "Convert SFR <> MSR", "固体燃料堆 ↔ 熔盐堆",
                "Create (Shift)", "创建（Shift）",
                "Delete (Shift)", "删除（Shift）",
                "Delete Stage (Hold Shift)", "删除阶段（按住 Shift）",
                "Delete Multiblock (Hold Shift)", "删除多方块结构（按住 Shift）",
                "Edit metadata", "编辑元数据",
                "Enter VR", "进入 VR",
                "Hot NaK", "高温钠钾合金",
                "Inner Radius", "内半径",
                "Core Size", "核心尺寸",
                "Toroid Width", "环宽",
                "Light, but darker", "浅色（较暗）",
                "Load Anyway", "仍要加载",
                "Made by ThizThizzyDizzy", "由 ThizThizzyDizzy 制作",
                " made by ", "，作者：",
                "New version available!", "有新版本可用！",
                "Set Texture", "设置纹理",
                "texture\nOr right click to generate a texture", "纹理\n右键单击可生成纹理",
                "Texture", "纹理",
                "Amount", "数量",
                "Change Theme", "更换主题",
                "Configurations", "配置",
                "Designs:", "设计：",
                "Early Concept Art", "早期概念美术",
                "Hut images", "小屋图像",
                "Libraries", "库",
                "Legacy Name", "旧名称",
                "Remove", "移除",
                "Modify", "修改",
                "Modify addon", "修改附加组件",
                "Create", "创建",
                "Choose one", "选择一项",
                "Import instead?", "改为导入？",
                "Standard", "标准",
                "Different", "另类",
                "ACTIVE", "运行中",
                "IDLE", "空闲",
                "Add", "添加",
                "Del", "删除",
                "Set", "设置",
                " value: ", " 值：",
                "Redo (Ctrl+", "重做（Ctrl+",
                "Undo (Ctrl+", "撤销（Ctrl+",
                "X Mirror", "X 轴镜像",
                "Y Mirror", "Y 轴镜像",
                "Z Mirror", "Z 轴镜像",
                "180 X Rotational", "180 度 X 轴旋转",
                "180 Y Rotational", "180 度 Y 轴旋转",
                "180 Z Rotational", "180 度 Z 轴旋转",
                "X Multiplier: ", "X 倍率：",
                "Y Multiplier: ", "Y 倍率：",
                "X Offset: ", "X 偏移：",
                "Y Offset: ", "Y 偏移：",
                "Something has gone horribly wrong!", "发生了严重错误！",
                "What's this doing here?", "这是什么？",
                "A fusion reactor for Nuclearcraft: Overhauled\nTHESE DO NOT EXIST INGAME!\nThis is just a prototype, and is VERY different from what they will be in-game", "核工艺：改版的聚变反应堆\n这些内容尚未在游戏内实装！\n这只是原型，与它们未来在游戏中的形态会有很大不同。",
                "Box tool (B)\nUse this tool to draw Rectangles or Cuboids of the same block\nHold CTRL to only place blocks where they are valid", "方框工具（B）\n使用此工具绘制由同一种方块组成的矩形或长方体\n按住 Ctrl 仅在有效位置放置方块",
                "Copy tool\nUse this to select an area to copy\nOnce an area is selected, click to paste that selection", "复制工具\n使用此工具选择要复制的区域\n选择区域后，单击即可粘贴所选内容",
                "Cut tool\nUse this to select an area to cut\nOnce an area is selected, click to paste that selection", "剪切工具\n使用此工具选择要剪切的区域\n选择区域后，单击即可粘贴所选内容",
                "Changes the reactor's coolant recipe to a random one from the list of allowed recipes", "将反应堆冷却剂配方更改为允许配方列表中的随机一项",
                "Changes the reactor's fuel to a random fuel from the list of allowed fuels", "将反应堆燃料更改为允许燃料列表中的随机一项",
                "Changes a random block in the reactor to a random block from the list of allowed blocks", "将反应堆中的随机方块替换为允许方块列表中的随机一项",
                "Adds a fuel cell at a random point in the reactor, optionally with moderator lines or other cells to ensure it can be valid", "在反应堆的随机位置添加燃料单元；可选地同时添加慢化剂线或其他单元以确保其有效",
                "All the base NuclearCraft: Overhauled multiblocks", "全部核工艺：改版基础多方块结构",
                "All the base NuclearCraft multiblocks", "全部核工艺基础多方块结构",
                "Contains general features appliccable to all multiblocks", "包含适用于全部多方块结构的通用功能",
                "Internal module for setup/testing purposes. Do not use.", "用于设置和测试的内部模块，请勿使用。",
                "A testbed for future overhaul fusion reactors.", "未来改版聚变反应堆的测试平台。",
                "Gives an adjusted efficiency score for overhaul SFRs based on neutron shield output", "根据中子屏蔽输出为改版固体燃料堆提供调整后的效率评分",
                "Gives multiblocks a Rainbow Factor based on how many different types of coolers/heatsinks/heaters/etc. they have", "根据多方块结构拥有的冷却器、散热器、加热器等类型数量赋予其彩虹因子",
                "Highlights the number of cells/vessels in a multiblock, and shows if it's a prime number", "突出显示多方块结构中的单元/燃料容器数量，并显示其是否为质数",
                "Choose element for tag or oredict:\n", "为标签或矿辞典选择元素：\n",
                "Cluster is not connected to a connector!", "簇未连接到连接器！",
                "Cluster is not connected to the casing!", "簇未连接到外壳！",
                "Cluster is heat-positive!", "簇的净热量为正！",
                "Cluster is penalized for overcooling!", "簇因过度冷却受到惩罚！",
                "No controller!", "缺少控制器！",
                "Too many controllers!", "控制器数量过多！",
                "Casing incomplete! (Missing ", "外壳不完整！（缺少 ",
                "Missing inlet!", "缺少入口！",
                "Missing outlet!", "缺少出口！",
                "Missing input vent!", "缺少输入排气口！",
                "Missing output vent!", "缺少输出排气口！",
                " input ports:", " 个输入端口：",
                " input port:", " 个输入端口：",
                " output ports:", " 个输出端口：",
                " output port:", " 个输出端口：",
                "Missing ", "缺少 ",
                "Invalid Bearing!", "轴承无效！",
                "Bearing Diameter: ", "轴承直径：",
                "Rotor Invalid!", "转子无效！",
                "Blade Suggestor", "叶片建议器",
                "Heatsink Suggestor", "散热器建议器",
                " similar clusters:", " 个相似簇：",
                " incomplete!", " 不完整！",
                " mb/t of whatever ", " mb/t 的 ",
                " mb/t of ", " mb/t 的 ",
                " gets turned into", "转化而成",
                "Input: ", "输入：",
                "Power Efficiency: ", "发电效率：",
                "Total Efficiency: ", "总效率：",
                "Rotor Efficiency: ", "转子效率：",
                "Coil Efficiency: ", "线圈效率：",
                "Throughput Efficiency: ", "吞吐效率：",
                "Ideality Multiplier: ", "理想度倍率：",
                "Total Heat: ", "总热量：",
                "Total Cooling: ", "总冷却量：",
                "Net Heat: ", "净热量：",
                "Overall Efficiency: ", "总体效率：",
                "Overall Heat Multiplier: ", "总体热量倍率：",
                "Sparsity Penalty Multiplier: ", "稀疏惩罚倍率：",
                "Shieldiness Factor: ", "屏蔽因子：",
                "Clusters: ", "簇：",
                "Total Irradiation: ", "总辐照量：",
                "Shutdown Factor: ", "停堆系数：",
                "Total Heating: ", "总产热：",
                "Net Heating: ", "净产热：",
                "Heat Multiplier: ", "热量倍率：",
                "Heat multiplier: ", "热量倍率：",
                "Cooling penalty mult: ", "冷却惩罚倍率：",
                "Efficiency: ", "效率：",
                "Total Output", "总产出",
                "Total Efficiency", "总效率",
                "Total Heat", "总热量",
                "Total Cooling", "总冷却量",
                "Net Heat", "净热量",
                "Heat Multiplier", "热量倍率",
                "No Fuel", "没有燃料",
                "No Recipe", "没有配方",
                "Fuel Cell ", "燃料单元 ",
                "Fuel Vessel ", "燃料容器 ",
                "Vessel Group ", "燃料容器组 ",
                "Vessel Group Primed", "燃料容器组已引燃",
                "Vessels", "个燃料容器",
                "Primed", "已引燃",
                "Self", "自身",
                "Augmented", "已增强",
                "Adjacent moderator lines: ", "相邻慢化剂线：",
                "Open Faces: ", "开放面：",
                "Bunching Factor: ", "聚集系数：",
                "Surface Factor: ", "表面积系数：",
                "Heat Produced: ", "产生热量：",
                "Positional Efficiency: ", "位置效率：",
                "Total Neutron Flux: ", "总中子通量：",
                "Criticality Factor: ", "临界系数：",
                "Flux Factor: ", "通量系数：",
                "Efficiency Factor: ", "效率系数：",
                "Efficiency factor: ", "效率系数：",
                "Efficiency multiplier: ", "效率倍率：",
                "Reflectivity: ", "反射率：",
                "Total flux: ", "总通量：",
                "Total heat: ", "总热量：",
                "Heat per flux: ", "每通量热量：",
                "Irradiator flux: ", "辐照器通量：",
                "Efficiency bonus: ", "效率加成：",
                "Neutron source: ", "中子源：",
                "Neutron Sources: ", "中子源数量：",
                "Heating Blanket ", "加热包层 ",
                "Breeding Blanket ", "增殖包层 ",
                "Liquid Distributor", "液体分配器",
                "Constants and Operators", "常量与运算符",
                "Constant", "常量",
                "Block is invalid", "方块无效",
                "Block is valid", "方块有效",
                "Clear Invalid Mutator", "清除无效变异器",
                "Increase Lining Thickness", "增加内衬厚度",
                "Decrease Lining Thickness", "减小内衬厚度",
                "Increase Inner Radius", "增加内半径",
                "Decrease Inner Radius", "减小内半径",
                "Increase Toroid Width", "增加环宽",
                "Decrease Toroid Width", "减小环宽",
                "Increase Core Size", "增加核心尺寸",
                "Decrease Core Size", "减小核心尺寸",
                "Decrase Core Size", "减小核心尺寸",
                "Delete (Hold Shift)", "删除（按住 Shift）",
                "Breeding Blanket Recipe", "增殖包层配方",
                "Breeding Blanket Stats", "增殖包层属性",
                "Coolant Recipe Stats", "冷却剂配方属性",
                "Irradiator Recipe Stats", "辐照器配方属性",
                "Active Cooler Recipe", "主动冷却器配方",
                "Fuel Cell", "燃料单元",
                "Fuel Vessel", "燃料容器",
                "Fuel Stats", "燃料属性",
                "Heater Recipe", "加热器配方",
                "Heater Stats", "加热器属性",
                "Irradiator Recipe", "辐照器配方",
                "Irradiator Stats", "辐照器属性",
                "Coolant Recipe", "冷却剂配方",
                "Coolant Vent", "冷却剂排气口",
                "Active Cooler", "主动冷却器",
                "Breeding Blanket", "增殖包层",
                "Heating Blanket", "加热包层",
                "Block Tag", "方块标签",
                "Fluid Tag", "流体标签",
                "Item Tag", "物品标签",
                "Greater or Equal", "大于或等于",
                "NuclearCraft: Overhauled", "核工艺：改版",
                "Fusion Test Configuration", "聚变测试配置",
                "Fusion Test", "聚变测试",
                "Prime Fuel", "质数燃料",
                "Next prime: ", "下一个质数：",
                "Axial pairs of ", "轴向配对数：",
                " at the same vertex", " 位于同一顶点",
                " at the same edge", " 位于同一边",
                "Requires ", "需要",
                "At least ", "至少 ",
                "Exactly ", "恰好 ",
                "Between ", "介于 ",
                " AND ", "且",
                " OR ", "或",
                " Heat Sink", "散热器",
                "Cell flux: ", "燃料单元中子通量：",
                " flux ", " 通量 ",
                ", Eff: ", "，效率：",
                "Cooling: ", "冷却：",
                "Durability: ", "耐久度：",
                "Iterations", "迭代次数",
                "per second", "每秒",
                "Recipe", "配方",
                "Stats", "属性",
                "Module", "模块",
                "Block", "方块",
                "Cell", "单元",
                "Vessel", "容器",
                "Heater", "加热器",
                "Heatsink", "散热器",
                "Cooler", "冷却器",
                "Casing", "外壳",
                "Controller", "控制器",
                "Connector", "连接器",
                "Conductor", "导体",
                "Reflector", "反射器",
                "Moderator", "慢化剂",
                "Shield", "屏蔽器",
                "Irradiator", "辐照器",
                "Vent", "排气口",
                "Port", "端口",
                "Rotor", "转子",
                "Blade", "叶片",
                "Stator", "定子",
                "Bearing", "轴承",
                "Shaft", "轴",
                "Coil", "线圈",
                "Glass", "玻璃",
                "Heating", "加热",
                "Cooling", "冷却",
                "Valid", "有效",
                "Invalid", "无效",
                "Cluster", "簇",
                "Axial", "轴向",
                "Depleted", "贫化",
                "Enriched", "浓缩",
                "Oxide", "氧化物",
                "Nitride", "氮化物",
                "Fluoride", "氟化物",
                "Alloy", "合金",
                "Uranium", "铀",
                "Thorium", "钍",
                "Plutonium", "钚",
                "Neptunium", "镎",
                "Americium", "镅",
                "Curium", "锔",
                "Berkelium", "锫",
                "Californium", "锎",
                "Bismuth", "铋",
                "Zirconium", "锆",
                "Manganese", "锰",
                "Nickel", "镍",
                "Cobalt", "钴",
                "Aluminum", "铝",
                "Coolant Heater Port", "冷却剂加热器端口",
                "Coolant Cooler Port", "冷却剂冷却器端口",
                "Coolant Heater", "冷却剂加热器",
                "Coolant Cooler", "冷却剂冷却器",
                "Fission Heat Sink", "裂变散热器",
                "Turbine Dynamo Coil", "涡轮发电线圈",
                "Turbine Rotor Blade", "涡轮转子叶片",
                "Turbine Rotor Stator", "涡轮转子定子",
                "Turbine Rotor Shaft", "涡轮转子轴",
                "Induction Turbine Magnet", "感应涡轮磁体",
                "Redstone Field Stabilizer", "红石场稳定器",
                "Redstone Field Converter", "红石场转换器",
                "Energy Extractor", "能量提取器",
                "Fuel Pellet", "燃料芯块",
                "Fuel Pebble", "燃料球",
                "Fuel Bundle", "燃料组件",
                "Carbon Dioxide", "二氧化碳",
                "Carbon Monoxide", "一氧化碳",
                "Activated Carbon", "活性炭",
                "Cold Eutectic NaK-Corium Mixture", "低温共晶钠钾合金-堆芯熔融物混合物",
                "Critical Exhaust Carbon Dioxide", "临界排气二氧化碳",
                "Compressed Carbon Dioxide", "压缩二氧化碳",
                "Actinium", "锕",
                "Aluminium", "铝",
                "Antimony", "锑",
                "Argon", "氩",
                "Arsenic", "砷",
                "Barium", "钡",
                "Calcium", "钙",
                "Carbon", "碳",
                "Cerium", "铈",
                "Chromium", "铬",
                "Darmstadtium", "达姆施塔特",
                "Einsteinium", "锿",
                "Europium", "铕",
                "Fermium", "镄",
                "Francium", "钫",
                "Gadolinium", "钆",
                "Gallium", "镓",
                "Germanium", "锗",
                "Hafnium", "铪",
                "Holmium", "钬",
                "Indium", "铟",
                "Iodine", "碘",
                "Iridium", "铱",
                "Krypton", "氪",
                "Lanthanum", "镧",
                "Lawrencium", "铹",
                "Lutetium", "镥",
                "Mendelevium", "钔",
                "Mercury", "汞",
                "Molybdenum", "钼",
                "Neodymium", "钕",
                "Neon", "氖",
                "Niobium", "铌",
                "Nitrogen", "氮",
                "Nobelium", "锘",
                "Osmium", "锇",
                "Oxygen", "氧",
                "Palladium", "钯",
                "Phosphorus", "磷",
                "Platinum", "铂",
                "Polonium", "钋",
                "Potassium", "钾",
                "Praseodymium", "镨",
                "Promethium", "钷",
                "Protactinium", "镤",
                "Radium", "镭",
                "Radon", "氡",
                "Rhenium", "铼",
                "Rhodium", "铑",
                "Rubidium", "铷",
                "Ruthenium", "钌",
                "Samarium", "钐",
                "Scandium", "钪",
                "Selenium", "硒",
                "Silicon", "硅",
                "Sodium", "钠",
                "Strontium", "锶",
                "Sulfur", "硫",
                "Tantalum", "钽",
                "Technetium", "锝",
                "Tellurium", "碲",
                "Terbium", "铽",
                "Thallium", "铊",
                "Thulium", "铥",
                "Titanium", "钛",
                "Tungsten", "钨",
                "Vanadium", "钒",
                "Xenon", "氙",
                "Ytterbium", "镱",
                "Yttrium", "钇",
                "Zinc", "锌",
                "ACTIVE COOLER", "主动冷却器",
                "COOLANT RECIPE", "冷却剂配方",
                "COOLER", "冷却器",
                "BLADE", "叶片",
                "COIL", "线圈",
                "CONNECTOR", "连接器",
                "Dynamo Coil", "发电线圈",
                "Field Stabilizer", "场稳定器",
                "Field Converter", "场转换器",
                "Fuel Pellet", "燃料芯块",
                "Fuel Pebble", "燃料球",
                "Fuel Bundle", "燃料组件",
                "Sodium-bonded", "钠键合",
                "Dioxide", "二氧化物",
                "Disilicide", "二硅化物",
                "Tempered", "回火",
                "Dynamo", "发电机",
                "Extractor", "提取器",
                "Stabilizer", "稳定器",
                "Converter", "转换器",
                "Magnet", "磁体",
                "Pellet", "芯块",
                "Pebble", "燃料球",
                "Bundle", "组件",
                "Ingot", "锭",
                "Dust", "粉末",
                "Ore", "矿石",
                "Sapling", "树苗",
                "Acacia", "金合欢",
                "Birch", "白桦",
                "Dark Oak", "深色橡木",
                "Cobblestone", "圆石",
                "Coal", "煤",
                "Brick", "砖",
                "Bone", "骨",
                "Cake", "蛋糕",
                "Caramel", "焦糖",
                "Buttermilk", "酪乳",
                "Bronze", "青铜",
                "Brass", "黄铜",
                "Constantan", "康铜",
                "Certus", "赛特斯",
                "High Pressure Steam", "高压蒸汽",
                "high_pressure_steam", "高压蒸汽",
                "Crap Steam", "劣质蒸汽",
                "Anti-Deuterium", "反氘",
                "Anti-Helium", "反氦",
                "Anti-Tritium", "反氚",
                "Zirconium Alloy", "锆合金",
                "Molybdenum Alloy", "钼合金",
                "Boron Arsenide", "砷化硼",
                "Carbon Arsenide", "砷化碳",
                "Barium Nitrate", "硝酸钡",
                "Nitrate", "硝酸盐",
                "Arsenide", "砷化物",
                "Aerotheum", "气凝质",
                "Baratol", "巴拉托炸药",
                "Billon", "比隆合金",
                "Blutonium", "蓝钚",
                "Caesium", "铯",
                "Carobbiite", "卡罗比石",
                "Corium", "堆芯熔融物",
                "Cryo-stablized", "低温稳定",
                "tempered", "回火",
                "Basic", "基础",
                "Liquid", "液体",
                "Hot", "高温",
                "Cold", "低温",
                "Critical", "临界",
                "Exhaust", "排气",
                "Compressed", "压缩",
                "Temperature", "温度",
                "Pressure", "压力",
                "Steam", "蒸汽",
                "NAK", "钠钾合金",
                "Eutectic", "共晶",
                "Mixture", "混合物",
                "TRISO", "三结构各向同性燃料",
                "FLiBe", "氟锂铍盐",
                "MOX", "混合氧化物燃料",
                "Molten", "熔融",
                "Salt", "盐",
                "Solution", "溶液",
                "Sink", "散热器",
                "Neutron", "中子",
                "Field", "场",
                "Metallic", "金属",
                "Pit", "燃料芯块",
                "Steel", "钢",
                "Source", "源",
                "Lapis", "青金石",
                "Glowstone", "萤石",
                "Stone", "石",
                "RECIPE", "配方",
                "FUEL", "燃料",
                "CELL", "单元",
                "VESSEL", "容器",
                "HEATSINK", "散热器",
                "MODERATOR", "慢化剂",
                "REFLECTOR", "反射器",
                "SHIELD", "屏蔽器",
                "IRRADIATOR", "辐照器",
                "STATOR", "定子",
                "Irradiated", "辐照",
                "Prismarine", "海晶石",
                "Purpur", "紫珀",
                "Nether", "下界",
                "Slime", "史莱姆",
                "End", "末地",
                "Energy", "能量",
                "Pumpkin", "南瓜",
                "Electrum", "琥珀金",
                "Milk", "牛奶",
                "Crystal", "水晶",
                "Carbide", "碳化物",
                "Fluix", "福鲁伊克斯",
                "Fluxed", "注能",
                "Extreme", "极致",
                "Doped", "掺杂",
                "Wafer", "晶圆",
                "Type", "类型",
                "Manager", "管理器",
                "Pressurized", "加压",
                "Thermoconducting", "导热",
                "Tough", "坚韧",
                "Hard", "坚硬",
                "Diboride", "二硼化物",
                "Zircaloy", "锆合金",
                "Ferroboron", "硼铁",
                "Rhodochrosite", "菱锰矿",
                "Egg", "鸡蛋",
                "Wheat", "小麦",
                "Chocolate", "巧克力",
                "Lumium", "流明",
                "Pie", "派",
                "Marshmallow", "棉花糖",
                "Pancake", "煎饼",
                "Sugar", "糖",
                "Computer", "计算机",
                "Nitinol", "镍钛合金",
                "Lava", "熔岩",
                "Invar", "因瓦合金",
                "Lantern", "灯笼",
                "Sponge", "海绵",
                "Mana", "魔力",
                "Petrotheum", "岩浆质",
                "Glowshroom", "荧光蘑菇",
                "Mysterious", "神秘",
                "Mithril", "秘银",
                "Flerovium", "鈇",
                "Magma", "岩浆",
                "Cream", "奶油",
                "Pyrotheum", "炽焱",
                "Ferrochrome", "铬铁",
                "Elektron", "电子合金",
                "Magnalium", "镁铝合金",
                "Hydronalium", "氢铝合金",
                "Monitor", "监视器",
                "Low", "低",
                "High", "高",
                "Ultra", "超",
                "Heavy", "重",
                "Radioactive", "放射性",
                "NaK", "钠钾合金",
                "mixture", "混合物",
                "molten", "熔融",
                "bonded", "键合",
                "Tritium", "氚",
                "COOLANT", "冷却剂",
                "HEATER", "加热器",
                "Anti", "反",
                "Signalum", "信素",
                "Cracker", "脆饼",
                "Villiaumite", "氟化钠矿",
                "Rutherfordium", "鑪",
                "Supercritical", "超临界",
                "Syrup", "糖浆",
                "Eggnog", "蛋奶酒",
                "Ice", "冰",
                "Sand", "沙",
                "Maple", "枫木",
                "Oak", "橡木",
                "Potato", "马铃薯",
                "Golden", "金质",
                "Prometheum", "普罗米修斯金属",
                "Yellorium", "黄素",
                "Trinitite", "三位一体矿",
                "Witherite", "毒重石",
                "Magnox", "镁诺克斯",
                "Ender", "末影",
                "Inlet", "入口",
                "Outlet", "出口",
                "Preheated", "预热",
                "Solid", "固体",
                "Quality", "品质",
                "Matrix", "矩阵",
                "Transparent", "透明",
                "Multiplier", "倍率",
                "Gasoline", "汽油",
                "Diesel", "柴油",
                "Activated", "活性",
                "Nugget", "粒",
                "Dirt", "泥土",
                "Pulverized", "粉碎",
                "Superalloyed", "高温合金",
                "Packed", "压实",
                "covered", "包覆",
                "S'more", "烤棉花糖夹心饼",
                "S'More", "烤棉花糖夹心饼",
                "S'meutectic", "棉花糖共晶",
                "S'molten", "棉花糖熔融",
                "S'moil", "棉花糖油",
                "S'Mingot", "棉花糖锭",
                "Th'morium", "棉钍",
                "Sea Lantern", "海晶灯",
                "End Stone", "末地石",
                "Endstone", "末地石",
                "Nether Brick", "下界砖",
                "Netherbrick", "下界砖",
                "Graham Cracker", "全麦脆饼",
                "Synthesis Gas", "合成气",
                "Fuel Oil", "燃料油",
                "Anti-Hydrogen", "反氢",
                "Hydride", "氢化物",
                "Hydrocarbon", "碳氢化合物",
                "Deuteride", "氘化物",
                "Ceramic Matrix", "陶瓷基体",
                "Matrix-Legierung", "基质合金",
                "Elektronlegierung", "电子合金",
                "Elektron60-Alloy", "电子合金 60",
                "Elektron192", "电子合金 192",
                "Elektron231", "电子合金 231",
                "Elektron90", "电子合金 90",
                "Edelstahl", "不锈钢",
                "Edle", "优质",
                "Copernicum", "鿔",
                "HSLA Steel", "高强度低合金钢",
                "Ultra Light", "超轻",
                "Unwieldy", "笨重",
                "Super", "超级",
                "Jungle", "丛林",
                "Kerosene", "煤油",
                "LPG", "液化石油气",
                "Schmeared", "涂布",
                "Spruce", "云杉",
                "Wasteland", "荒地",
                "Erbium", "铒",
                "Extremecake", "极致蛋糕",
                "Gelid", "凝胶态",
                "Lukewarm", "温热",
                "Methane", "甲烷",
                "Nichrome", "镍铬合金",
                "Osmiridium", "锇铱合金",
                "Slimy", "黏液",
                "Steelcake", "钢蛋糕",
                "Unfinished", "未完成",
                "Well", "井",
                "Earth", "土",
                "Magnet", "磁体",
                "SiC", "碳化硅",
                "CMC", "陶瓷基复合材料",
                "Bronzemagnet", "青铜磁体",
                "Chromiumagnet", "铬磁体",
                "Constantanmagnet", "康铜磁体",
                "Ferroboronmagnet", "硼铁磁体",
                "Invarmagnet", "因瓦合金磁体",
                "Iridiumagnet", "铱磁体",
                "Ironmagnet", "铁磁体",
                "Leadmagnet", "铅磁体",
                "Lithiumagnet", "锂磁体",
                "Manganesemagnet", "锰磁体",
                "Neodymiumagnet", "钕磁体",
                "Nickelmagnet", "镍磁体",
                "Osmiumagnet", "锇磁体",
                "Potassiumagnet", "钾磁体",
                "Samariumagnet", "钐磁体",
                "Siliconcarbidemagnet", "碳化硅磁体",
                "Steelmagnet", "钢磁体",
                "Tinmagnet", "锡磁体",
                "Tungstenmagnet", "钨磁体",
                "Zincmagnet", "锌磁体",
                "TODO tooltip", "功能开发中",
                "Overhaul Fusion Reactor", "改版聚变反应堆",
                "Fusion Reactor", "聚变反应堆",
                "Overhaul Turbine", "改版涡轮机",
                "Overhaul Distiller", "改版蒸馏器",
                "Distiller", "蒸馏器",
                "Condition", "条件",
                "Operator", "运算符",
                "And", "且",
                "Greater", "大于",
                "Equal", "等于",
                "Less", "小于",
                "Not", "非",
                "floor", "向下取整",
                "random", "随机",
                "int", "整数",
                "float", "浮点数",
                "null", "空值",
                "byte", "字节",
                "short", "短整数",
                "long", "长整数",
                "double", "双精度浮点数",
                "bool", "布尔值",
                "boolean", "布尔值",
                "str", "字符串",
                "True", "真",
                "False", "假",
                "INTERNAL", "内部",
                "Core", "核心",
                "Overhaul SFRs are Solid-Fueled Fission reactors in NuclearCraft: Overhauled", "改版固体燃料堆是核工艺：改版中的固体燃料裂变反应堆",
                "If you have blocks called \"Cooler\" instead of \"Heat Sink\", you are playing Underhaul", "如果你的方块名为“冷却器”而非“散热器”，说明你使用的是旧版。",
                "Underhaul SFRs are Solid-Fueled Fission reactors in NuclearCraft", "旧版固体燃料堆是核工艺中的固体燃料裂变反应堆",
                "If you have blocks called \"Heat Sink\" instead of \"Cooler\", you are playing Overhaul", "如果你的方块名为“散热器”而非“冷却器”，说明你使用的是改版。",
                "Overhaul SFRs are Solid-Fueled Fission reactors in NuclearCraft: Overhauled\nIf you have blocks called \"Cooler\" instead of \"Heat Sink\", you are playing Underhaul", "改版固体燃料堆是核工艺：改版中的固体燃料裂变反应堆\n如果你的方块名为“冷却器”而非“散热器”，说明你使用的是旧版。",
                "Underhaul SFRs are Solid-Fueled Fission reactors in NuclearCraft\nIf you have blocks called \"Heat Sink\" instead of \"Cooler\", you are playing Overhaul", "旧版固体燃料堆是核工艺中的固体燃料裂变反应堆\n如果你的方块名为“散热器”而非“冷却器”，说明你使用的是改版。",
                "Overhaul MSRs are Molten Salt Fission reactors in NuclearCraft: Overhauled", "改版熔盐堆是核工艺：改版中的熔盐裂变反应堆",
                "Overhaul Turbines are Turbines in NuclearCraft: Overhauled", "改版涡轮机是核工艺：改版中的涡轮机",
                "Overhaul Distillers are Distillers in NuclearCraft: Overhauled\nWow, who could have guessed?", "改版蒸馏器是核工艺：改版中的蒸馏器\n确实令人意外。",
                "Suggests adding Fuel cells to increase output", "建议添加燃料单元以提高产出",
                "Suggests adding Fuel cells with moderators to increase efficiency and output", "建议添加带慢化剂的燃料单元以提高效率和产出",
                "Suggests adding Fuel vessels with moderators to increase efficiency and output", "建议添加带慢化剂的燃料容器以提高效率和产出",
                "Suggests adding Moderator blocks to increase efficiency", "建议添加慢化剂方块以提高效率",
                "Suggests adding or replacing active coolers to cool the reactor", "建议添加或替换主动冷却器以冷却反应堆",
                "Suggests adding or replacing passive coolers to cool the reactor", "建议添加或替换被动冷却器以冷却反应堆",
                "Suggests adding or replacing heat sinks to cool the reactor", "建议添加或替换散热器以冷却反应堆",
                "Suggests adding or replacing heaters to cool the reactor", "建议添加或替换加热器以冷却反应堆",
                "Suggests adding, removing, or replacing coils for higher coil efficiency", "建议添加、移除或替换线圈以提高线圈效率",
                "Suggests blades and stators for higher rotor efficiency and ideality", "建议使用叶片和定子以提高转子效率与理想膨胀率",
                "Suggests changing moderator lines to increase efficiency or irradiation", "建议调整慢化剂线以提高效率或辐照量",
                "Suggests changing single moderators to increase efficiency or irradiation", "建议调整单个慢化剂以提高效率或辐照量",
                "Suggests adding or replacing heat sinks to increase the reactor's rainbow factor", "建议添加或替换散热器以提高反应堆的彩虹因子",
                "Suggests adding or replacing passive coolers to increase the reactor's rainbow factor.", "建议添加或替换被动冷却器以提高反应堆的彩虹因子。",
                "Move tool (M)\nUse this to move or copy selections\nHold Ctrl to copy selections\nHold Ctrl+Shift to copy selection, and keep the old selection", "移动工具（M）\n使用此工具移动或复制选区\n按住 Ctrl 复制选区\n按住 Ctrl+Shift 复制选区并保留原选区",
                "Paste tool\nSelect a region, and press Ctrl-X or Ctrl+C to cut or copy the selection and open this tool.\nThen click any location in your reactor to paste the selection in multiple places.\nPress Escape or select a different tool when done.\nPress Ctrl+V to ready the most recently copied selection", "粘贴工具\n选择区域后，按 Ctrl+X 或 Ctrl+C 剪切或复制选区，并打开此工具。\n然后单击反应堆中的任意位置，将选区粘贴到多个位置。\n完成后按 Esc 或选择其他工具。\n按 Ctrl+V 准备最近复制的选区",
                "Pencil tool (P)\nUse this tool to draw blocks one at a time\nHold CTRL to only place blocks where they are valid", "铅笔工具（P）\n使用此工具逐个绘制方块\n按住 Ctrl 仅在有效位置放置方块",
                "Line tool (L)\nUse this tool to draw blocks in a line through the multiblock\nHold CTRL to only place blocks where they are valid", "直线工具（L）\n使用此工具在多方块结构中沿直线绘制方块\n按住 Ctrl 仅在有效位置放置方块",
                "Select tool (S)\nUse this to select areas of the reactor\nCtrl-click to select multiple selections\nShift-click to select Groups of blocks that require each other\nAlt-click to select clusters\nEdits can only be made inside of selections (unless there are no selections)\nPress Delete to delete the selected area\nPress Escape to clear selection", "选择工具（S）\n使用此工具选择反应堆区域\n按住 Ctrl 单击可选择多个选区\n按住 Shift 单击可选择相互依赖的方块组\n按住 Alt 单击可选择簇\n只能在选区内编辑（没有选区时除外）\n按删除键删除所选区域\n按 Esc 清除选区",
                "Adjacent moderator line (", "相邻慢化剂线（",
                "Adjacent to fuel cell (", "与燃料单元相邻（",
                "Has neutron source (", "具有中子源（",
                "Neutron source path (", "中子源路径（",
                "Targeted block (", "目标方块（",
                "Valid moderator line (", "有效慢化剂线（",
                "Missing blade", "缺少叶片",
                "Missing casing", "缺少外壳",
                "Invalid cluster!", "无效簇！",
                "No target", "无目标",
                "Unknown Rule", "未知规则",
                "NCPF Element", "NCPF 元素",
                "Legacy Names", "旧名称",
                "Legacy Block", "旧版方块",
                "Legacy Fluid", "旧版流体",
                "Legacy Item", "旧版物品",
                "Legacy Recipe", "旧版配方",
                "Liquid Distributer", "液体分配器",
                "Poloidal Electromagnet", "极向电磁体",
                "Toroidal Electromagnet", "环向电磁体",
                "Process Port", "处理端口",
                "Recipe Ports", "配方端口",
                "Reboiling Unit", "再沸器",
                "Reflux Unit", "回流器",
                "Reservoir Port", "储液端口",
                "Sieve Assembly", "筛板组件",
                "Sieve Tray", "筛盘",
                "Neutron Shield", "中子屏蔽器",
                "Neutron Source", "中子源",
                "Power Generation: ", "发电量：",
                "Total output: ", "总产出：",
                "Prime Fuels", "质数燃料",
                "Previous Prime: ", "上一个质数：",
                "Rainbow Score: ", "彩虹评分：",
                "Rainbow Factor", "彩虹因子",
                "Quantum Traversed Efficiency Score", "量子传输效率评分",
                "Quantum Traversed Efficiency: ", "量子传输效率：",
                "Random Coolant Recipe Mutator", "随机冷却剂配方变异器",
                "Random Quantity Mutator", "随机数量变异器",
                "Random Block Mutator", "随机方块变异器",
                "Random Cell Mutator", "随机单元变异器",
                "Random Fuel Mutator", "随机燃料变异器",
                "Single Mutator", "单次变异器",
                "Mutator Quantity", "变异器数量",
                "Runs once per iteration", "每次迭代运行一次",
                "Runs a random number of times per iteration\nEvenly distributed between min and max", "每次迭代随机运行若干次\n在最小值和最大值之间均匀分布",
                "Replaces all invalid blocks in the reactor with air", "将反应堆中的所有无效方块替换为空气",
                "Less or Equal", "小于或等于",
                "Not Equal", "不等于",
                "Overhaul Distiller Configuration", "改版蒸馏器配置",
                "Overhaul Distiller", "改版蒸馏器",
                "Overhaul Turbine", "改版涡轮机",
                "Overhaul MSR", "改版熔盐堆",
                "Overhaul SFR", "改版固体燃料堆",
                "Underhaul SFR", "旧版固体燃料堆",
                "Heat Sink", "散热器",
                "Passive Cooler", "被动冷却器",
                "Fuel Cell", "燃料单元",
                "Fuel Vessel", "燃料容器",
                "Fuels: ", "燃料：",
                " (Prime)", "（质数）",
                "A tool from Tinker's Construct (not a multiblock)", "来自匠魂的工具（不是多方块结构）",
                "Make sure all the parts are actually there", "确保所有部件确实存在",
                "Maximize mining level, then mining speed", "优先最大化采矿等级，再最大化采矿速度",
                "Maximize Defense and Toughness", "最大化防御和韧性",
                "Maximize draw speed", "最大化拉弓速度",
                "Maximize bow range", "最大化弓射程",
                "Maximize damage", "最大化伤害",
                "Tinker's tools, (not multiblocks)", "匠魂工具（不是多方块结构）",
                "Tinker's Construct", "匠魂",
                "Tinker Tool", "匠魂工具",
                "Two ", "两个 ",
                "Three ", "三个 ",
                "Legacy", "旧版",
                "Fluid", "流体",
                "Item", "物品",
                "Names", "名称",
                "Target", "目标",
                "Quantity", "数量",
                "Random", "随机",
                "Single", "单次",
                "Prime", "质数",
                " and ", " 和 ",
                "Aye", "是",
                "Alright", "好的",
                "Awknowledged", "已知悉",
                "Skip", "跳过",
                "Thanks", "谢谢",
                "Yep", "是",
                "Power", "功率",
                "Heat", "热量",
                "Efficiency", "效率",
                "Output", "产出",
                "Input", "输入",
                "Fuel", "燃料",
                "Coolant", "冷却剂",
                "Reactor", "反应堆",
                "Turbine", "涡轮机",
                "Fusion", "聚变",
                "Fission", "裂变",
                "Overhaul", "改版",
                "Underhaul", "旧版",
                "Functions", "功能",
                "Elements", "元素",
                "Add ", "添加 ",
                "Delete ", "删除 ",
                "Modify ", "修改 ");
        entries.addAll(translations.entrySet());
        entries.sort(Comparator.comparingInt((Map.Entry<String, String> entry) -> entry.getKey().length()).reversed());
    }

    private static void add(Map<String, String> translations, String... values){
        for(int i = 0; i<values.length; i += 2)translations.put(values[i], values[i + 1]);
    }

    @Override
    public String localize(String text){
        if(text == null || text.isEmpty())return text;
        String cached = cache.get(text);
        if(cached!=null)return cached;
        String localized = text;
        for(Map.Entry<String, String> entry : entries)localized = replace(localized, entry.getKey(), entry.getValue());
        cache.put(text, localized);
        return localized;
    }

    private static String replace(String text, String source, String replacement){
        int index = text.indexOf(source);
        if(index<0)return text;
        StringBuilder localized = new StringBuilder(text.length());
        int copiedUntil = 0;
        while(index>=0){
            int end = index+source.length();
            if(hasWordBoundaries(text, source, index, end)){
                localized.append(text, copiedUntil, index);
                localized.append(replacement);
                copiedUntil = end;
            }
            index = text.indexOf(source, index+1);
        }
        if(copiedUntil==0)return text;
        localized.append(text, copiedUntil, text.length());
        return localized.toString();
    }

    private static boolean hasWordBoundaries(String text, String source, int start, int end){
        return (!isWordCharacter(source.charAt(0))||start==0||!isWordCharacter(text.charAt(start-1)))
                &&(!isWordCharacter(source.charAt(source.length()-1))||end==text.length()||!isWordCharacter(text.charAt(end)));
    }

    private static boolean isWordCharacter(char character){
        return character>='A'&&character<='Z'
                ||character>='a'&&character<='z'
                ||character>='0'&&character<='9'
                ||character=='_';
    }
}
